// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ControleProcedure.DATA.Models
{
    public partial class ClientesProcedimentos
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        public int? CpIdCliente { get; set; }
        public int? CpIdProcedimento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CpDataProcedimento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CpDataSuporte { get; set; }
        public bool? CpFinalizado { get; set; }

        [ForeignKey(nameof(CpIdCliente))]
        [InverseProperty(nameof(Cliente.ClientesProcedimentos))]
        public virtual Cliente CpIdClienteNavigation { get; set; }
        [ForeignKey(nameof(CpIdProcedimento))]
        [InverseProperty(nameof(Servicos.ClientesProcedimentos))]
        public virtual Servicos CpIdProcedimentoNavigation { get; set; }
    }
}