// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace controlProcedure.DATA.Models
{
    public partial class ClientesProcedimentos
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        public int? CpIdCliente { get; set; }
        public int? CpIdProcedimento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CpDataProcedimento { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CpDataSuporte { get; set; }
        public bool? CpFinalizado { get; set; }

        [ForeignKey("CpIdCliente")]
        [InverseProperty("ClientesProcedimentos")]
        public virtual Cliente CpIdClienteNavigation { get; set; }
        [ForeignKey("CpIdProcedimento")]
        [InverseProperty("ClientesProcedimentos")]
        public virtual Servicos CpIdProcedimentoNavigation { get; set; }
    }
}