// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace controlProcedure.DATA.Models
{
    public partial class Servicos
    {
        public Servicos()
        {
            ClientesProcedimentos = new HashSet<ClientesProcedimentos>();
        }

        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("procedNome")]
        [StringLength(50)]
        [Unicode(false)]
        public string ProcedNome { get; set; }
        [Column("procedLocal")]
        [StringLength(50)]
        [Unicode(false)]
        public string ProcedLocal { get; set; }
        [Column("procedObservacao")]
        [StringLength(200)]
        [Unicode(false)]
        public string ProcedObservacao { get; set; }

        [InverseProperty("CpIdProcedimentoNavigation")]
        public virtual ICollection<ClientesProcedimentos> ClientesProcedimentos { get; set; }
    }
}